### ISSUE TITLE
The range of importance field

### ISSUE THREAD

**Issue by ChanwooLucioLee** [swsnu/swpp2020-team13#5]
The importance field in Task model is defined as FloatField.
Thus, the value of importance can be literally any number, which does not seem logical.

What would be a good range of numbers for importance?
ex) 1~10, 0~5, 0~100 ...

Would it be better to make it discrete or continuous?
ex) [0, 5] vs {0, 1, 2, 3, 4, 5}

**Comment by jiyewise** [comment]
I think the importance range should be 1-5, as it is visualized with 5 stars.
Either 1,2,3,4,5 (discrete integers) or continuous float are fine I think..

**Comment by ChanwooLucioLee** [comment]
@jiyewise If we allow continuous float for importance then we will need to validate if the number is either one of 1, 2, 3, 4, and 5 in frontend or backend.  Does that sound okay for you?

**Comment by jiyewise** [comment]
@ChanwooLucioLee I thought the validation could be if x <= 5 and x >=1 sort of thing if we allow continuous floats. Is that impossible? 
p.s. I actually think both discrete and continuous are fine..guess we can ask other's ideas about this topic.

**Comment by ChanwooLucioLee** [comment]
@jiyewise Implementation will not be difficult. Let's see how other teammates think about it.

**Comment by songbird39** [comment]
I agree with going simple and discrete since too many choices rather burden the user with handling the standards. If the choices are 0~100, how much importance does 35 have? They will have to go back to other tasks to see how they set all the importances, and the decision will be unnecessarily complicated and tiresome. I believe there won't be any need to classify & order in more than 5 groups, and users themselves will have to define their own standards and use only those numbers. (even when they are given full integers or even floating numbers, most people will stay with 10s and at most 5s... even if they don't, I believe their choices should be limited for their sake)

For the implementation, I like the idea of a choice from [1, 2, 3, 4, 5], but this is rather a personal preference.

**Comment by songbird39** [comment]
Also a question: to make more importance ranks(let's say, 10) necessary, there should be enough tasks to sort (more than 10). Although the total tasks might be much more than any number, the user will mostly stay in the daily view: where the tasks are 1) already classified by goals, and 2) unlikely to be more than a 5 star system can manage.

**Comment by ChanwooLucioLee** [comment]
@songbird39 You're right. Let's employ choice field to handle importance.
